#ifndef __DEFINES_H__
#define __DEFINES_H__

#define NUM_TEXTURE_LAYERS            6
#define BILLBOARD_TEXTURE_SIZE     2048
#define COLOR_CORNER_SIZE            32

#define CORNER_WHITE_X                 (BILLBOARD_TEXTURE_SIZE - COLOR_CORNER_SIZE)
#define CORNER_WHITE_Y                 (BILLBOARD_TEXTURE_SIZE - COLOR_CORNER_SIZE)
#define CORNER_WHITE_W                 (COLOR_CORNER_SIZE)
#define CORNER_WHITE_H                 (COLOR_CORNER_SIZE)

#define CORNER_BLACK_X                 (BILLBOARD_TEXTURE_SIZE - 2 * COLOR_CORNER_SIZE)
#define CORNER_BLACK_Y                 (BILLBOARD_TEXTURE_SIZE - COLOR_CORNER_SIZE)
#define CORNER_BLACK_W                 (COLOR_CORNER_SIZE)
#define CORNER_BLACK_H                 (COLOR_CORNER_SIZE)

#define CORNER_TRANSPARENT_X           (BILLBOARD_TEXTURE_SIZE - 3 * COLOR_CORNER_SIZE)
#define CORNER_TRANSPARENT_Y           (BILLBOARD_TEXTURE_SIZE - 3 * COLOR_CORNER_SIZE)
#define CORNER_TRANSPARENT_W           (COLOR_CORNER_SIZE)
#define CORNER_TRANSPARENT_H           (COLOR_CORNER_SIZE)

#endif

