#include "strings.h"

const char
	*s_uPerspective = "uPerspective",
	*s_uPL_Position = "uPL_Position",
	*s_uPL_Color = "uPL_Color",
	*s_uPL_Constant = "uPL_Constant",
	*s_uPL_Linear = "uPL_Linear",
	*s_uPL_Quadratic = "uPL_Quadratic",
	*s_uShadow = "uShadow",
	*s_uTexture = "uTexture",
	*s_uPositionMatrix = "uPositionMatrix",
	*s_uSelectionID = "uSelectionID",
	*s_uLayerDiffuse = "uLayerDiffuse",
	*s_uSamplerDiffuse = "uSamplerDiffuse",
	*s_uLayerSpecular = "uLayerSpecular",
	*s_uSamplerSpecular = "uSamplerSpecular",
	*s_uLayerEmissive = "uLayerEmissive",
	*s_uSamplerEmissive = "uSamplerEmissive",
	*s_uLayerNormal = "uLayerNormal",
	*s_uSamplerNormal = "uSamplerNormal",
	*s_uColorDiffuse = "uColorDiffuse",
	*s_uColorSpecular = "uColorSpecular",
	*s_uColorEmissive = "uColorEmissive",
	*s_uViewPosition = "uViewPosition",
	*s_uShininess = "uShininess",
	*s_uDark = "uDark",
	*s_uLightMatrix = "uLightMatrix",
	*s_uDL_Used = "uDL_Used",
	*s_uDL_Position = "uDL_Position",
	*s_uDL_Color = "uDL_Color",
	*s_uSamplerShadow = "uSamplerShadow",
	*s_uCubemap = "uCubemap",
	*s_uColor = "uColor",
	*s_uHorizontal = "uHorizontal",
	*s_uSampler = "uSampler",
	*s_uTextureSize = "uTextureSize",
	*s_uProjection = "uProjection",
	*s_uResolution = "uResolution";

